class Enum:
    CONNECTING = "connect"
    REGISTRATION = "register"
    IS_JOINED = "is_joined"
    STUDENT_LIST = "student_list"
    CONNECTED_STUDENT_LIST = "connected_student_list"
    SEND_TO_TEACHER = "send_to_teacher"
    TEACHER_MESSAGE = "teacher_message"
    YES = "yes"
    NO = "no"
    CONNECT_TO_STUDENT = "connect_to_student"
    DISCONNECT = "disconnect"
    THE_NEXT_FRAME = "the_next_frame"
    STUDENTS_FOR_TEACHER = "students_for_teacher"
    ADD_FEEDBACKS = "add_feedbacks"
    CHECK_IF_FIRST_TIME_CONNECTED = "check_if_first_time_connected"
    LAST_LESSON = "last_lesson"